name: Enforce Jira Key in Pull Request Message

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  enforce-jira-key:
    runs-on: ubuntu-latest

    steps:
    - name: Check Jira Key in Pull Request Message
      run: |
        pull_request_message=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
                            jq -r '.body')

        if [[ ! "$pull_request_message" =~ [A-Z]{1,10}-[0-9]+ ]]; then
          echo "ERROR: Pull request message does not contain a valid Jira key."
          exit 1
        fi
